#!/usr/bin/php
<?php


require 'autoload.php';


$Loader = new Pboy\Loader\Loader;


$Conf = $Loader->getService('Config', 'Ini');


$Cli        = $Loader->getService('Cli',        $Conf);
$Task       = $Loader->getService('Task',       $Conf);

array_shift($argv);

$task = array_pop($argv);


if ($task) {
    $status = $Task->execute($task);

    if ($status) {
        $Cli->write('Done');
    }

} else {
    $Cli->write($Task->execute('synopsis'));

}

