#!/usr/bin/php
<?php

/*  ____ Include autoloads ________________________________
    
    Composer's autoload first, then our built-in
*/
require 'vendor/autoload.php';


/*  ____ Init Config ______________________________________

    Class has to be hard coded since Loader needs a Config
    object to do its job.
    This also means than Config object, at least when loaded
    from here, has no dependencies managed.
*/
$Config = new Pboy\Config\Ini;


/*  ____ Init Loader ______________________________________

    As for Config, class is hard coded here.
    Dependencies are self managed but Config is hard-loaded
*/
$Loader = new Pboy\Loader\Loader(
                array('Config' => $Config)
            );


/*  ____ Init more needed classes  ________________________
    
    $Io to say something
    $Task to do something
*/
$Io     = $Loader->getService('Io');
$Task   = $Loader->getService('Task');


/*  ____ Execution ________________________________________

    For now command has to be after arguments due to getopt()
    using some global variable that we can't rewrite.
    This only fact makes it untestable and suggest we should
    add our own options parser (or some free lib).
*/

try {

    $task = $Io->getTask();

    $options = $Io->getOptions($task);

} catch (UnexpectedValueException $e) {
    $Io->write($e->getMessage());
    $Io->help($task);
}

try{

    if ($task) {
        $status = $Task->execute($task, $options);

        if ($status === true) {
            $Io->write('Done');
        } else {
            $Io->write($status);
        }

    } else {
        $Io->write($Task->execute('synopsis'));    
    }

} catch (Exception $e) {
    
    $Io->write($e->getMessage());

    if (array_key_exists('verbose', $options)) {
        $Io->write('Debug information:');
        $Io->write($e->getMessage());
    }
}


