#!/usr/bin/php
<?php


require 'autoload.php';


$Loader = new Pboy\Loader\Loader;


$Conf = $Loader->getService('Config', 'Ini');


$Io         = $Loader->getService('Io', $Conf);
$Task       = $Loader->getService('Task', $Conf);

array_shift($argv);

$task = array_pop($argv);


if ($task) {
    $status = $Task->execute($task);

    if ($status) {
        $Io->write('Done');
    }

} else {
    $Io->write($Task->execute('synopsis'));

}

